# For 2016-2017 data joins
non_join_features.default = c(
    "id_parcel", "fips", "latitude",
    "longitude", "pooltypeid2", "pooltypeid7",
    "rawcensustractandblock", "tax_building", "tax_total",
    "tax_year","tax_land","tax_property",
    "tax_delinquency", "tax_delinquency_year", "censustractandblock",
    "census", "tract_number", "tract_block")


# For 2016-2017 data joins
join_features.default=c(
"build_year",
"area_basement",
"area_patio",
"area_shed",
"area_pool",
"area_lot",
"area_garage",
"area_firstfloor_finished",
"area_total_calc",
"area_base",
"area_live_finished",
"area_liveperi_finished",
"area_total_finished",
"area_unknown",
"num_unit",
"num_story",
"num_room",
"num_bathroom",
"num_bedroom",
"num_bathroom_calc",
"num_bath",
"num_75_bath",
"num_fireplace",
"num_pool",
"num_garage",
"region_county",
"region_city",
"region_zip",
"region_neighbor",
"deck",
"zoning_property",
"zoning_landuse",
"zoning_landuse_county",
"flag_fireplace",
"flag_tub",
"flag_tub_extra",
"quality",
"framing",
"material",
"story",
"heating",
"aircon",
"architectural_style")
